apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  name: ds-chat-gpt-app
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      serviceAccountName: ds-mkt-ltv@ds-mkt.iam.gserviceaccount.com
      timeoutSeconds: 600
      containers:
      - image: europe-docker.pkg.dev/ds-mkt/app/ds-chat-gpt-backend:v0.0.1rc14
        env:
          - name: PROJECT
            value: ds-mkt
          - name: DATASET
            value: ds_chat_gpt
          - name: CLOUD_RUN
            value: "True"
          - name: ENVIRONMENT
            value: PROD
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "2Gi"
#        volumeMounts:
#        - name: bucket
#          mountPath: /bucket

# IAM & Admin > Identity-Aware Proxy